[build]
  command = "CI=false npm run build"
  publish = "build"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
